## 08 numpy 聚合运算

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.07851465, 0.57847422, 0.58702173, 0.72657326, 0.0223579 ,
       0.1291925 , 0.90964279, 0.42199661, 0.13575945, 0.34487414,
       0.93615579, 0.3352131 , 0.17862418, 0.769497  , 0.09340243,
       0.79054332, 0.52802118, 0.15424386, 0.21691821, 0.94924642,
       0.77002081, 0.6893108 , 0.30888177, 0.48211053, 0.875893  ,
       0.15697215, 0.49821062, 0.18374421, 0.72489882, 0.5642188 ,
       0.30228115, 0.66252549, 0.49656208, 0.57766655, 0.0098562 ,
       0.19988642, 0.06380985, 0.74488249, 0.84729017, 0.83347665,
       0.44732527, 0.07080194, 0.62386401, 0.50845539, 0.80659934,
       0.81548813, 0.82488143, 0.88215787, 0.8543864 , 0.29544728,
       0.18573209, 0.22641155, 0.26839028, 0.91318325, 0.06924534,
       0.11597869, 0.67906437, 0.76405709, 0.81773448, 0.29473216,
       0.75691596, 0.31165511, 0.3951025 , 0.08028212, 0.40148787,
       0.52439331, 0.36024489, 0.36636101, 0.29716762, 0.67910282,
       0.38485658, 0.27436036, 0.73323078, 0.81547538, 0.11690

In [3]:
sum(L)

51.59941264749394

In [4]:
np.sum(L)

51.599412647493914

In [5]:
big_array = np.random.rand(1000000)
%time sum(big_array)
%time np.sum(big_array)

CPU times: user 141 ms, sys: 477 µs, total: 142 ms
Wall time: 142 ms
CPU times: user 671 µs, sys: 42 µs, total: 713 µs
Wall time: 467 µs


500024.8656295295

In [6]:
np.min(big_array)

2.597030359652308e-07

In [7]:
np.max(big_array)

0.9999993778549546

In [8]:
big_array.min()

2.597030359652308e-07

In [9]:
big_array.max()

0.9999993778549546

In [10]:
big_array.sum()

500024.8656295295

In [12]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(X) # 所有元素的和

120

In [14]:
np.sum(X, axis=0) # 每一列的和 沿着行方向 对每列进行运算 == 把这个轴压缩

array([24, 28, 32, 36])

In [15]:
np.sum(X, axis=1) # 沿着列方向 对每一行进行运算

array([ 6, 22, 38, 54])

In [16]:
np.prod(X)

0

In [17]:
np.prod(X+1)

20922789888000

In [18]:
np.mean(X)

7.5

In [19]:
np.median(X)

7.5

In [22]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [23]:
np.median(v) 

2.0

In [24]:
np.percentile(big_array, q=50) # q代表百分位点 50%的元素小于 0.5002958805770883

0.5002958805770883

In [25]:
np.median(big_array)

0.5002958805770883

In [26]:
np.percentile(big_array, q=100)

0.9999993778549546

In [27]:
np.max(big_array)

0.9999993778549546

In [28]:
for percent in [0, 25, 50 ,100]: # 重要的百分位点
    print(np.percentile(big_array, q=percent))

2.597030359652308e-07
0.24991252958742083
0.5002958805770883
0.9999993778549546


In [29]:
np.var(big_array)

0.083347818111486

In [30]:
np.std(big_array)

0.2887002218764059

In [39]:
x = np.random.normal(0, 1, size=1000000)

In [40]:
np.mean(x)

0.00013615454064919594

In [41]:
np.std(x)

0.999235872284206