## 09 numpy 索引

In [28]:
import numpy as np
x = np.random.normal(0, 1, size=1000000)

In [29]:
np.min(x)

-4.674445934191868

In [30]:
np.argmin(x) # x中最小值的下表index

695484

In [31]:
np.argmax(x)

429674

In [32]:
x[319219]

-0.723092474802095

In [33]:
np.max(x)

5.082109366542165

### 排序和使用索引

In [34]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
np.random.shuffle(x)
x

array([14,  3,  4,  5, 11,  7, 10, 12,  6,  9, 13, 15,  8,  1,  0,  2])

In [36]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
x

array([14,  3,  4,  5, 11,  7, 10, 12,  6,  9, 13, 15,  8,  1,  0,  2])

In [38]:
x.sort()

In [39]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
X = np.random.randint(10, size=(4, 4)) # 随机矩阵
X

array([[7, 1, 7, 6],
       [1, 8, 1, 5],
       [9, 4, 3, 9],
       [0, 6, 9, 2]])

In [41]:
np.sort(X)

array([[1, 6, 7, 7],
       [1, 1, 5, 8],
       [3, 4, 9, 9],
       [0, 2, 6, 9]])

In [42]:
np.sort(X, axis = 1) # 沿着 列 把每一行排序

array([[1, 6, 7, 7],
       [1, 1, 5, 8],
       [3, 4, 9, 9],
       [0, 2, 6, 9]])

In [43]:
np.sort(X, axis = 0) # 沿着行 把每一列排序

array([[0, 1, 1, 2],
       [1, 4, 3, 5],
       [7, 6, 7, 6],
       [9, 8, 9, 9]])

In [44]:
np.random.shuffle(x)
x

array([ 1, 10, 13,  3,  4,  6,  8,  5, 11,  0, 15, 12, 14,  7,  2,  9])

In [46]:
np.argsort(x) #把数组x排序后输出每一个元素在原数组的index

array([ 9,  0, 14,  3,  4,  7,  5, 13,  6, 15,  1,  8, 11,  2, 12, 10])

In [47]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  8, 10, 11,  6, 15, 12, 14,  7, 13,  9])

In [48]:
np.argpartition(x, 3)

array([ 0,  9, 14,  3,  4,  7,  6,  1,  8,  5, 10, 11, 12, 13,  2, 15])

In [49]:
X

array([[7, 1, 7, 6],
       [1, 8, 1, 5],
       [9, 4, 3, 9],
       [0, 6, 9, 2]])

In [52]:
np.argsort(X, axis = 1)

array([[1, 3, 0, 2],
       [0, 2, 3, 1],
       [2, 1, 0, 3],
       [0, 3, 1, 2]])

In [53]:
np.argsort(X, axis = 0)

array([[3, 0, 1, 3],
       [1, 2, 2, 1],
       [0, 3, 0, 0],
       [2, 1, 3, 2]])

In [55]:
np.partition(X, 2, axis = 1)

array([[1, 6, 7, 7],
       [1, 1, 5, 8],
       [3, 4, 9, 9],
       [0, 2, 6, 9]])

In [56]:
np.argpartition(X, 2, axis = 1)

array([[1, 3, 2, 0],
       [0, 2, 3, 1],
       [2, 1, 0, 3],
       [0, 3, 1, 2]])