## 10 Fancy Indexing

In [42]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
x[3]

3

In [44]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [45]:
x[3:9:2]

array([3, 5, 7])

In [46]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [47]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

In [48]:
ind = np.array([[0,2]
                ,[1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [49]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [51]:
X[0,col]

array([1, 2, 3])

In [52]:
X[:2, col] # 前两行的对应col点的元素 0,1 这两行 和 1,2,3 这三列的值

array([[1, 2, 3],
       [5, 6, 7]])

In [53]:
col = [True, False, True, True] # 重要！！批量比较的结果

In [54]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 比较

In [55]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [57]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [58]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [59]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [60]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [61]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [63]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
np.sum(x <= 3)

4

In [66]:
np.count_nonzero(x <= 3) # x<=3 结果是一个布尔数组，true为1 false为0

4

In [67]:
np.any(x == 0)

True

In [68]:
np.any(x < 0)

False

In [70]:
np.all(x >= 0)

True

In [71]:
np.all(x > 0)

False

In [72]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
np.sum(X % 2 == 0)

8

In [74]:
np.sum(X%2 == 0, axis = 1) # 沿着列的方向 看每一行有多少偶数

array([2, 2, 2, 2])

In [76]:
np.sum(X%2 == 0, axis = 0) # 沿着行的方向 看每一列有多少偶数

array([4, 0, 4, 0])

In [79]:
np.all(X>0, axis=1) #在列的方向上 看每一行有没有大于零的元素

array([False,  True,  True,  True])

In [80]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
np.sum((x>3) & (x<10)) # (x>3),(x<10) 两个数组 按照相应的索引按照分别进行与或的运算 得到的结果 依然是一个数组

6

In [85]:
np.sum((x%2==0)|(x>10))

11

In [88]:
np.sum(~(x==0)) # 非零数字个数

15

In [89]:
np.sum(x>0)

15

In [92]:
x[x<5] #所有满足条件的值

array([0, 1, 2, 3, 4])

In [97]:
X[X[:,-1] % 3 ==0, -1]

array([ 3, 15])

In [98]:
X[X[:,-1] % 3 ==0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

#### Pandas 对数据预处理 然后转化为numpy的矩阵 然后进行机器学习的算法